#!/usr/bin/env bash
# This script displays specific user details from /etc/passwd
while IFS= read -r line; do
  username=$(echo "$line" | cut -d: -f1)
  uid=$(echo "$line" | cut -d: -f3)
  home=$(echo "$line" | cut -d: -f6)
  echo "$username:$uid:$home"
done < /etc/passwd
