#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays data ordered by occurrences
file="${1:-apache-access.log}"
awk '{print $1, $9}' "$file" | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
