#!/usr/bin/env bash
# Group visitors by IP and HTTP status code and display occurrence count
awk '{print $1, $9}' "${1:-apache-access.log}" | sort | uniq -c | sort -k1,1nr -k2,2 -k3,3 | awk '{print $1, $2, $3}'
