#!/bin/bash
perl -lane '($w,$s)=(0,0), map({$w=$w*5+$_} split(//,$F[0])), map({$s=$s*5+$_} split(//,$F[1])), @b=split(//,"bestchol"), print join("", map { $b[$_] } split(//, sprintf("%o", $w+$s)))' <<< "$(echo "$WATER" | tr 'water' '01234') $(echo "$STIR" | tr 'stir.' '01234')"
